name: Build

on:
  workflow_dispatch: 
  push:

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 1

      - name: Generate build files
        run: mkdir build && cd build && cmake ../ -G "Visual Studio 16 2019" -A Win32

      - name: Build
        run: |
          cd build
          cmake --build . --config Release

      - name: Create a folder for release
        shell: bash
        run: |
          mkdir dist
          cd dist
          mkdir components
          mkdir -p qawno/include
          cd ..
          mv ./build/src/Release/omp-websocket.dll ./dist/components/omp-websocket.dll
          mv ./websockets.inc ./dist/qawno/include/websockets.inc

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: omp-ws-win
          path: dist/*

  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 1

      - name: Install gcc/g++-multilib
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt install gcc-9-multilib g++-9-multilib libstdc++-10-dev:i386

      - name: Generate build files
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32

      - name: Build
        run: |
          cd build
          cmake --build . --parallel $(nproc)

      - name: Create a folder for release
        shell: bash
        run: |
          mkdir dist
          cd dist
          mkdir components
          mkdir -p qawno/include
          cd ..
          mv ./build/src/omp-websocket.so ./dist/components/omp-websocket.so
          mv ./websockets.inc ./dist/qawno/include/websockets.inc

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: omp-ws-linux
          path: dist/*